# Generated by Django 3.1.7 on 2021-08-21 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='general_covid_19',
            old_name='Comments',
            new_name='comments',
        ),
        migrations.RenameField(
            model_name='general_covid_19',
            old_name='number_Of_Staff_who_tested_positive_to_covid_19_at_hubs',
            new_name='number_Of_staff_who_tested_positive_to_covid_19_at_hubs',
        ),
        migrations.RenameField(
            model_name='general_covid_19',
            old_name='Request_to_brti_from_the_laboratory',
            new_name='request_to_brti_from_the_laboratory',
        ),
    ]
