# Generated by Django 3.1.7 on 2021-08-30 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specimensreceivedbrtiweekly',
            name='reasons6',
            field=models.IntegerField(default=0, verbose_name='Plasma'),
        ),
    ]
