# Generated by Django 3.2.4 on 2021-08-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specimens_received_covid_19',
            name='samples_Referred_to_Name',
            field=models.CharField(default='null', max_length=500),
        ),
    ]
