# Generated by Django 3.2.6 on 2021-08-30 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_customuser_lab'),
    ]

    operations = [
        migrations.AddField(
            model_name='specimensrunbrtivleid',
            name='key',
            field=models.TextField(default='vl', max_length=5),
        ),
        migrations.AddField(
            model_name='specimensrunbrtivlweekly',
            name='key',
            field=models.TextField(default='vl', max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='lab',
            field=models.CharField(blank=True, choices=[('Victoria Falls', 'Victoria_Falls'), ('Bindura', 'Bindura')], max_length=200),
        ),
        migrations.AlterField(
            model_name='generalbrticovid19',
            name='dayofweek',
            field=models.TextField(default='brti', max_length=30),
        ),
        migrations.AlterField(
            model_name='specimensrunbrtivleid',
            name='dayofweek',
            field=models.TextField(default='Total', max_length=30),
        ),
    ]
