# Generated by Django 3.1.7 on 2021-09-01 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20210901_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specimensrunbrtivleid',
            name='ncsclosedthisweek1',
        ),
        migrations.RemoveField(
            model_name='specimensrunbrtivleid',
            name='ncsnotyetclosed1',
        ),
        migrations.RemoveField(
            model_name='specimensrunbrtivleid',
            name='totalncsfromaudit1',
        ),
    ]
