# Generated by Django 3.1.7 on 2021-08-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20210821_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='General_covid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Monday', max_length=200)),
                ('general_comments_regarding_testing_and_challenges_faced_by_the_laboratory', models.CharField(max_length=5000, null=True)),
                ('number_of_staff_who_tested_positive_to_covid_19_at_vl_lab', models.IntegerField()),
                ('number_Of_staff_who_tested_positive_to_covid_19_at_hubs', models.IntegerField()),
                ('number_of_staff_who_have_been_vaccinated', models.IntegerField()),
                ('comments', models.TextField(default='null', max_length=5000, null=True)),
                ('request_to_brti_from_the_laboratory', models.CharField(max_length=5000, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='General_covid_19',
        ),
    ]
