# Generated by Django 3.1.7 on 2021-08-30 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20210830_1011'),
        ('pages', '0003_auto_20210830_0912'),
    ]

    operations = [
    ]
