# Generated by Django 3.1.7 on 2021-08-26 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20210825_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricoutagebrtivlweekly',
            name='dayofweek',
            field=models.TextField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Monday', max_length=30),
        ),
        migrations.AlterField(
            model_name='electricoutagebrtivlweekly',
            name='lab',
            field=models.TextField(default='brti', max_length=30),
        ),
        migrations.AlterField(
            model_name='electricoutagebrtivlweekly',
            name='user',
            field=models.TextField(default='root', max_length=25),
        ),
        migrations.AlterField(
            model_name='electricoutagebrtiweekly',
            name='dayofweek',
            field=models.TextField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Monday', max_length=30),
        ),
        migrations.AlterField(
            model_name='electricoutagebrtiweekly',
            name='lab',
            field=models.TextField(default='brti', max_length=30),
        ),
        migrations.AlterField(
            model_name='electricoutagebrtiweekly',
            name='user',
            field=models.TextField(default='root', max_length=25),
        ),
        migrations.AlterField(
            model_name='generalbrticovid19',
            name='Requesttobrtifromthelaboratory',
            field=models.TextField(default='.', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='generalbrticovid19',
            name='dayofweek',
            field=models.TextField(choices=[('NMRL', 'NMRL'), ('Mpilo', 'Mpilo'), ('BRIDH', 'BRIDH'), ('NTBRL', 'NTBRL'), ('Gweru', 'Gweru'), ('Chinhoyi', 'Chinhoyi'), ('Masvingo', 'Masvingo'), ('eid', 'eid'), ('Victoria Falls', 'Victoria Falls'), ('Bindura', 'Bindura'), ('Kadoma', 'Kadoma'), ('Marondera', 'Marondera'), ('St Lukes', 'St Lukes'), ('Gwanda', 'Gwanda'), ('Total', 'Total')], default='NMRL', max_length=30),
        ),
        migrations.AlterField(
            model_name='generalbrticovid19',
            name='generalcommentsregardingtestingandchallengesfacedbythelaboratory',
            field=models.TextField(default='.', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='generalbrticovid19',
            name='lab',
            field=models.TextField(default='brti', max_length=30),
        ),
        migrations.AlterField(
            model_name='generalbrticovid19',
            name='user',
            field=models.TextField(default='root', max_length=25),
        ),
        migrations.AlterField(
            model_name='generalcovid19',
            name='Requesttobrtifromthelaboratory',
            field=models.TextField(default='.', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='generalcovid19',
            name='dayofweek',
            field=models.TextField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Monday', max_length=30),
        ),
        migrations.AlterField(
            model_name='generalcovid19',
            name='generalcommentsregardingtestingandchallengesfacedbythelaboratory',
            field=models.TextField(default='.', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='generalcovid19',
            name='lab',
            field=models.TextField(default='brti', max_length=30),
        ),
        migrations.AlterField(
            model_name='generalcovid19',
            name='user',
            field=models.TextField(default='root', max_length=25),
        ),
        migrations.AlterField(
            model_name='machinedowntimereagentstockouttoolbrticovid19',
            name='dayofweek',
            field=models.TextField(choices=[('NMRL', 'NMRL'), ('Mpilo', 'Mpilo'), ('BRIDH', 'BRIDH'), ('NTBRL', 'NTBRL'), ('Gweru', 'Gweru'), ('Chinhoyi', 'Chinhoyi'), ('Masvingo', 'Masvingo'), ('eid', 'eid'), ('Victoria Falls', 'Victoria Falls'), ('Bindura', 'Bindura'), ('Kadoma', 'Kadoma'), ('Marondera', 'Marondera'), ('St Lukes', 'St Lukes'), ('Gwanda', 'Gwanda'), ('Total', 'Total')], default='NMRL', max_length=30),
        ),
        migrations.AlterField(
            model_name='machinedowntimereagentstockouttoolbrticovid19',
            name='lab',
            field=models.TextField(default='brti', max_length=30),
        ),
        migrations.AlterField(
            model_name='machinedowntimereagentstockouttoolbrticovid19',
            name='user',
            field=models.TextField(default='root', max_length=25),
        ),
        migrations.AlterField(
            model_name='reasonsforfailurebrtivleid',
            name='dayofweek',
            field=models.TextField(choices=[('NMRL', 'NMRL'), ('Mpilo', 'Mpilo'), ('BRIDH', 'BRIDH'), ('NTBRL', 'NTBRL'), ('Gweru', 'Gweru'), ('Chinhoyi', 'Chinhoyi'), ('Masvingo', 'Masvingo'), ('eid', 'eid'), ('Victoria Falls', 'Victoria Falls'), ('Bindura', 'Bindura'), ('Kadoma', 'Kadoma'), ('Marondera', 'Marondera'), ('St Lukes', 'St Lukes'), ('Gwanda', 'Gwanda'), ('Total', 'Total')], default='NMRL', max_length=30),
        ),
        migrations.AlterField(
            model_name='reasonsforfailurebrtivleid',
            name='lab',
            field=models.TextField(default='brti', max_length=30),
        ),
        migrations.AlterField(
            model_name='reasonsforfailurebrtivleid',
            name='user',
            field=models.TextField(default='root', max_length=25),
        ),
        migrations.AlterField(
            model_name='reasonsforfailurebrtivlweekly',
            name='dayofweek',
            field=models.TextField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Monday', max_length=30),
        ),
        migrations.AlterField(
            model_name='reasonsforfailurebrtivlweekly',
            name='lab',
            field=models.TextField(default='brti', max_length=30),
        ),
        migrations.AlterField(
            model_name='reasonsforfailurebrtivlweekly',
            name='user',
            field=models.TextField(default='root', max_length=25),
        ),
        migrations.AlterField(
            model_name='reasonsforfailurebrtiweekly',
            name='dayofweek',
            field=models.TextField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Monday', max_length=30),
        ),
        migrations.AlterField(
            model_name='reasonsforfailurebrtiweekly',
            name='lab',
            field=models.TextField(default='brti', max_length=30),
        ),
        migrations.AlterField(
            model_name='reasonsforfailurebrtiweekly',
            name='user',
            field=models.TextField(default='root', max_length=25),
        ),
        migrations.AlterField(
            model_name='specimensreceivedbrticovid19',
            name='comment',
            field=models.TextField(default='.', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='specimensreceivedbrticovid19',
            name='dayofweek',
            field=models.TextField(choices=[('NMRL', 'NMRL'), ('Mpilo', 'Mpilo'), ('BRIDH', 'BRIDH'), ('NTBRL', 'NTBRL'), ('Gweru', 'Gweru'), ('Chinhoyi', 'Chinhoyi'), ('Masvingo', 'Masvingo'), ('eid', 'eid'), ('Victoria Falls', 'Victoria Falls'), ('Bindura', 'Bindura'), ('Kadoma', 'Kadoma'), ('Marondera', 'Marondera'), ('St Lukes', 'St Lukes'), ('Gwanda', 'Gwanda'), ('Total', 'Total')], default='NMRL', max_length=30),
        ),
        migrations.AlterField(
            model_name='specimensreceivedbrticovid19',
            name='lab',
            field=models.TextField(default='brti', max_length=30),
        ),
        migrations.AlterField(
            model_name='specimensreceivedbrticovid19',
            name='user',
            field=models.TextField(default='root', max_length=25),
        ),
        migrations.AlterField(
            model_name='specimensreceivedbrtivleid',
            name='dayofweek',
            field=models.TextField(choices=[('NMRL', 'NMRL'), ('Mpilo', 'Mpilo'), ('BRIDH', 'BRIDH'), ('NTBRL', 'NTBRL'), ('Gweru', 'Gweru'), ('Chinhoyi', 'Chinhoyi'), ('Masvingo', 'Masvingo'), ('eid', 'eid'), ('Victoria Falls', 'Victoria Falls'), ('Bindura', 'Bindura'), ('Kadoma', 'Kadoma'), ('Marondera', 'Marondera'), ('St Lukes', 'St Lukes'), ('Gwanda', 'Gwanda'), ('Total', 'Total')], default='NMRL', max_length=30),
        ),
        migrations.AlterField(
            model_name='specimensreceivedbrtivleid',
            name='lab',
            field=models.TextField(default='brti', max_length=30),
        ),
        migrations.AlterField(
            model_name='specimensreceivedbrtivleid',
            name='user',
            field=models.TextField(default='root', max_length=25),
        ),
        migrations.AlterField(
            model_name='specimensreceivedbrtiweekly',
            name='dayofweek',
            field=models.TextField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Monday', max_length=30),
        ),
        migrations.AlterField(
            model_name='specimensreceivedbrtiweekly',
            name='lab',
            field=models.TextField(default='brti', max_length=30),
        ),
        migrations.AlterField(
            model_name='specimensreceivedbrtiweekly',
            name='user',
            field=models.TextField(default='root', max_length=25),
        ),
        migrations.AlterField(
            model_name='specimensreceivedcovid19',
            name='comment',
            field=models.TextField(default='.', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='specimensreceivedcovid19',
            name='dayofweek',
            field=models.TextField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Monday', max_length=30),
        ),
        migrations.AlterField(
            model_name='specimensreceivedcovid19',
            name='lab',
            field=models.TextField(default='brti', max_length=30),
        ),
        migrations.AlterField(
            model_name='specimensreceivedcovid19',
            name='samplesReferredtoName',
            field=models.TextField(default='null', max_length=30),
        ),
        migrations.AlterField(
            model_name='specimensreceivedcovid19',
            name='user',
            field=models.TextField(default='root', max_length=25),
        ),
        migrations.AlterField(
            model_name='specimensrecievedbrtivlweekly',
            name='dayofweek',
            field=models.TextField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Monday', max_length=30),
        ),
        migrations.AlterField(
            model_name='specimensrecievedbrtivlweekly',
            name='lab',
            field=models.TextField(default='brti', max_length=30),
        ),
        migrations.AlterField(
            model_name='specimensrecievedbrtivlweekly',
            name='user',
            field=models.TextField(default='root', max_length=25),
        ),
        migrations.AlterField(
            model_name='specimensrunbrticovid19',
            name='dayofweek',
            field=models.TextField(choices=[('NMRL', 'NMRL'), ('Mpilo', 'Mpilo'), ('BRIDH', 'BRIDH'), ('NTBRL', 'NTBRL'), ('Gweru', 'Gweru'), ('Chinhoyi', 'Chinhoyi'), ('Masvingo', 'Masvingo'), ('eid', 'eid'), ('Victoria Falls', 'Victoria Falls'), ('Bindura', 'Bindura'), ('Kadoma', 'Kadoma'), ('Marondera', 'Marondera'), ('St Lukes', 'St Lukes'), ('Gwanda', 'Gwanda'), ('Total', 'Total')], default='NMRL', max_length=30),
        ),
        migrations.AlterField(
            model_name='specimensrunbrticovid19',
            name='lab',
            field=models.TextField(default='brti', max_length=30),
        ),
        migrations.AlterField(
            model_name='specimensrunbrticovid19',
            name='user',
            field=models.TextField(default='root', max_length=25),
        ),
        migrations.AlterField(
            model_name='specimensrunbrtivleid',
            name='dayofweek',
            field=models.TextField(choices=[('NMRL', 'NMRL'), ('Mpilo', 'Mpilo'), ('BRIDH', 'BRIDH'), ('NTBRL', 'NTBRL'), ('Gweru', 'Gweru'), ('Chinhoyi', 'Chinhoyi'), ('Masvingo', 'Masvingo'), ('EID', 'EID'), ('Victoria Falls', 'Victoria Falls'), ('Bindura', 'Bindura'), ('Kadoma', 'Kadoma'), ('Marondera', 'Marondera'), ('St Lukes', 'St Lukes'), ('Gwanda', 'Gwanda'), ('Total', 'Total')], default='NMRL', max_length=30),
        ),
        migrations.AlterField(
            model_name='specimensrunbrtivleid',
            name='lab',
            field=models.TextField(default='brti', max_length=30),
        ),
        migrations.AlterField(
            model_name='specimensrunbrtivleid',
            name='user',
            field=models.TextField(default='root', max_length=25),
        ),
        migrations.AlterField(
            model_name='specimensrunbrtivlweekly',
            name='dayofweek',
            field=models.TextField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Monday', max_length=30),
        ),
        migrations.AlterField(
            model_name='specimensrunbrtivlweekly',
            name='lab',
            field=models.TextField(default='brti', max_length=30),
        ),
        migrations.AlterField(
            model_name='specimensrunbrtivlweekly',
            name='user',
            field=models.TextField(default='root', max_length=25),
        ),
        migrations.AlterField(
            model_name='specimensrunbrtiweekly',
            name='dayofweek',
            field=models.TextField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Monday', max_length=30),
        ),
        migrations.AlterField(
            model_name='specimensrunbrtiweekly',
            name='lab',
            field=models.TextField(default='brti', max_length=30),
        ),
        migrations.AlterField(
            model_name='specimensrunbrtiweekly',
            name='user',
            field=models.TextField(default='root', max_length=25),
        ),
        migrations.AlterField(
            model_name='specimensruncovid19',
            name='dayofweek',
            field=models.TextField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Monday', max_length=30),
        ),
        migrations.AlterField(
            model_name='specimensruncovid19',
            name='lab',
            field=models.TextField(default='brti', max_length=30),
        ),
        migrations.AlterField(
            model_name='specimensruncovid19',
            name='user',
            field=models.TextField(default='root', max_length=25),
        ),
        migrations.AlterField(
            model_name='top3brtivlweekly',
            name='lab',
            field=models.TextField(default='brti', max_length=30),
        ),
        migrations.AlterField(
            model_name='top3brtivlweekly',
            name='tatmediancollectiontopickupdbshrs',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top3brtivlweekly',
            name='tatmediancollectiontopickupplasmahrs',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top3brtivlweekly',
            name='tatmedianintralabdbsdays',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top3brtivlweekly',
            name='tatmedianintralabplasmadays',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top3brtivlweekly',
            name='tatmedianresultshubtoclinicdbsdays',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top3brtivlweekly',
            name='tatmedianresultshubtoclinicplasmadays',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top3brtivlweekly',
            name='tatmedianresultsvllabtohubdbsdays',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top3brtivlweekly',
            name='tatmedianresultsvllabtohubplasmadays',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top3brtivlweekly',
            name='tatmedianspecimenhubtovllabdbsdays',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top3brtivlweekly',
            name='tatmedianspecimenhubtovllabplasmadays',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top3brtivlweekly',
            name='user',
            field=models.TextField(default='root', max_length=25),
        ),
        migrations.AlterField(
            model_name='top3brtiweekly',
            name='lab',
            field=models.TextField(default='brti', max_length=30),
        ),
        migrations.AlterField(
            model_name='top3brtiweekly',
            name='tatmediancollectiontopickupdbshrs',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top3brtiweekly',
            name='tatmediancollectiontopickupplasmahrs',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top3brtiweekly',
            name='tatmedianintralabdbsdays',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top3brtiweekly',
            name='tatmedianintralabplasmadays',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top3brtiweekly',
            name='tatmedianresultshubtoclinicdbsdays',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top3brtiweekly',
            name='tatmedianresultshubtoclinicplasmadays',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top3brtiweekly',
            name='tatmedianresultsvllabtohubdbsdays',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top3brtiweekly',
            name='tatmedianresultsvllabtohubplasmadays',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top3brtiweekly',
            name='tatmedianspecimenhubtovllabdbsdays',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top3brtiweekly',
            name='tatmedianspecimenhubtovllabplasmadays',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top3brtiweekly',
            name='user',
            field=models.TextField(default='root', max_length=25),
        ),
        migrations.AlterField(
            model_name='top3covid19',
            name='lab',
            field=models.TextField(default='brti', max_length=30),
        ),
        migrations.AlterField(
            model_name='top3covid19',
            name='numberofcompletedtransmittalsheetreceived',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top3covid19',
            name='numberofdaystat1',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top3covid19',
            name='numberofdaystat2',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top3covid19',
            name='numberofdaystat3',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top3covid19',
            name='numberofdaystattotal',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top3covid19',
            name='user',
            field=models.TextField(default='root', max_length=25),
        ),
        migrations.AlterField(
            model_name='top4brtivlweekly',
            name='lab',
            field=models.TextField(default='brti', max_length=30),
        ),
        migrations.AlterField(
            model_name='top4brtivlweekly',
            name='machinenumberofmachinebreakdownsabbott',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top4brtivlweekly',
            name='machinenumberofmachinebreakdownsbmx',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top4brtivlweekly',
            name='machinenumberofmachinebreakdownshologicpanther',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top4brtivlweekly',
            name='machinenumberofmachinebreakdownsroche',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top4brtivlweekly',
            name='machinereasonsabbott',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top4brtivlweekly',
            name='machinereasonsbmx',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top4brtivlweekly',
            name='machinereasonshologicpanther',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top4brtivlweekly',
            name='machinereasonsroche',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top4brtivlweekly',
            name='user',
            field=models.TextField(default='root', max_length=25),
        ),
        migrations.AlterField(
            model_name='top4brtiweekly',
            name='lab',
            field=models.TextField(default='brti', max_length=30),
        ),
        migrations.AlterField(
            model_name='top4brtiweekly',
            name='machinenumberofmachinebreakdownsabbott',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top4brtiweekly',
            name='machinenumberofmachinebreakdownsbmx',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top4brtiweekly',
            name='machinenumberofmachinebreakdownshologicpanther',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top4brtiweekly',
            name='machinenumberofmachinebreakdownsroche',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top4brtiweekly',
            name='machinereasonsabbott',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top4brtiweekly',
            name='machinereasonsbmx',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top4brtiweekly',
            name='machinereasonshologicpanther',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top4brtiweekly',
            name='machinereasonsroche',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top4brtiweekly',
            name='user',
            field=models.TextField(default='root', max_length=25),
        ),
        migrations.AlterField(
            model_name='top5brtivlweekly',
            name='lab',
            field=models.TextField(default='brti', max_length=30),
        ),
        migrations.AlterField(
            model_name='top5brtivlweekly',
            name='machinedowntimedaysabbott',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top5brtivlweekly',
            name='machinedowntimedaysbmx',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top5brtivlweekly',
            name='machinedowntimedayshologicpanther',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top5brtivlweekly',
            name='machinedowntimedaysroche',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top5brtivlweekly',
            name='machinereasonsabbott',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top5brtivlweekly',
            name='machinereasonsbmx',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top5brtivlweekly',
            name='machinereasonshologicpanther',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top5brtivlweekly',
            name='machinereasonsroche',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top5brtivlweekly',
            name='machinetimetakenfordowntimetoberesolvedabbott',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top5brtivlweekly',
            name='machinetimetakenfordowntimetoberesolvedbmx',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top5brtivlweekly',
            name='machinetimetakenfordowntimetoberesolvedhologicpanther',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top5brtivlweekly',
            name='machinetimetakenfordowntimetoberesolvedroche',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top5brtivlweekly',
            name='user',
            field=models.TextField(default='root', max_length=25),
        ),
        migrations.AlterField(
            model_name='top5brtiweekly',
            name='lab',
            field=models.TextField(default='brti', max_length=30),
        ),
        migrations.AlterField(
            model_name='top5brtiweekly',
            name='machinedowntimedaysabbott',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top5brtiweekly',
            name='machinedowntimedaysbmx',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top5brtiweekly',
            name='machinedowntimedayshologicpanther',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top5brtiweekly',
            name='machinedowntimedaysroche',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top5brtiweekly',
            name='machinereasonsabbott',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top5brtiweekly',
            name='machinereasonsbmx',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top5brtiweekly',
            name='machinereasonshologicpanther',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top5brtiweekly',
            name='machinereasonsroche',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top5brtiweekly',
            name='machinetimetakenfordowntimetoberesolvedabbott',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top5brtiweekly',
            name='machinetimetakenfordowntimetoberesolvedbmx',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top5brtiweekly',
            name='machinetimetakenfordowntimetoberesolvedhologicpanther',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top5brtiweekly',
            name='machinetimetakenfordowntimetoberesolvedroche',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top5brtiweekly',
            name='user',
            field=models.TextField(default='root', max_length=25),
        ),
        migrations.AlterField(
            model_name='top61brtiweekly',
            name='lab',
            field=models.TextField(default='brti', max_length=30),
        ),
        migrations.AlterField(
            model_name='top61brtiweekly',
            name='machineamountofliquidwasteabbott',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top61brtiweekly',
            name='machineamountofliquidwastebmx',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top61brtiweekly',
            name='machineamountofliquidwastehologicpanther',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top61brtiweekly',
            name='machineamountofliquidwasteroche',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top61brtiweekly',
            name='user',
            field=models.TextField(default='root', max_length=25),
        ),
        migrations.AlterField(
            model_name='top6brtivlweekly',
            name='lab',
            field=models.TextField(default='brti', max_length=30),
        ),
        migrations.AlterField(
            model_name='top6brtivlweekly',
            name='machinereasonsabbott',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top6brtivlweekly',
            name='machinereasonsbmx',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top6brtivlweekly',
            name='machinereasonshologicpanther',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top6brtivlweekly',
            name='machinereasonsroche',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top6brtivlweekly',
            name='machinestockoutdaysabbott',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top6brtivlweekly',
            name='machinestockoutdaysbmx',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top6brtivlweekly',
            name='machinestockoutdayshologicpanther',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top6brtivlweekly',
            name='machinestockoutdaysroche',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top6brtivlweekly',
            name='user',
            field=models.TextField(default='root', max_length=25),
        ),
        migrations.AlterField(
            model_name='top6brtiweekly',
            name='lab',
            field=models.TextField(default='brti', max_length=30),
        ),
        migrations.AlterField(
            model_name='top6brtiweekly',
            name='machinereasonsabbott',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top6brtiweekly',
            name='machinereasonsbmx',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top6brtiweekly',
            name='machinereasonshologicpanther',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top6brtiweekly',
            name='machinereasonsroche',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top6brtiweekly',
            name='machinestockoutdaysabbott',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top6brtiweekly',
            name='machinestockoutdaysbmx',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top6brtiweekly',
            name='machinestockoutdayshologicpanther',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top6brtiweekly',
            name='machinestockoutdaysroche',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top6brtiweekly',
            name='user',
            field=models.TextField(default='root', max_length=25),
        ),
        migrations.AlterField(
            model_name='top7brtivlweekly',
            name='lab',
            field=models.TextField(default='brti', max_length=30),
        ),
        migrations.AlterField(
            model_name='top7brtivlweekly',
            name='reagent1',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top7brtivlweekly',
            name='reagent10',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top7brtivlweekly',
            name='reagent11',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top7brtivlweekly',
            name='reagent12',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top7brtivlweekly',
            name='reagent13',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top7brtivlweekly',
            name='reagent2',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top7brtivlweekly',
            name='reagent3',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top7brtivlweekly',
            name='reagent4',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top7brtivlweekly',
            name='reagent5',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top7brtivlweekly',
            name='reagent6',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top7brtivlweekly',
            name='reagent7',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top7brtivlweekly',
            name='reagent8',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top7brtivlweekly',
            name='reagent9',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top7brtivlweekly',
            name='reagenttestsloanedouttootherlabsmonthsofstockabbott',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top7brtivlweekly',
            name='reagenttestsloanedouttootherlabsmonthsofstockbmx',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top7brtivlweekly',
            name='reagenttestsloanedouttootherlabsmonthsofstockhologicpanther',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top7brtivlweekly',
            name='reagenttestsloanedouttootherlabsmonthsofstockroche',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top7brtivlweekly',
            name='reagenttestsloanedouttootherlabsreagentloanedtowhichlababbott',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top7brtivlweekly',
            name='reagenttestsloanedouttootherlabsreagentloanedtowhichlabbmx',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top7brtivlweekly',
            name='reagenttestsloanedouttootherlabsreagentloanedtowhichlabroche',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top7brtivlweekly',
            name='reagenttestsloanedouttootherlabsstockonhandabbott',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top7brtivlweekly',
            name='reagenttestsloanedouttootherlabsstockonhandbmx',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top7brtivlweekly',
            name='reagenttestsloanedouttootherlabsstockonhandhologicpanther',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top7brtivlweekly',
            name='reagenttestsloanedouttootherlabsstockonhandroche',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top7brtivlweekly',
            name='reagenttestsloanedouttootherlabstestsavailableabbott',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top7brtivlweekly',
            name='reagenttestsloanedouttootherlabstestsavailablebmx',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top7brtivlweekly',
            name='reagenttestsloanedouttootherlabstestsavailablehologicpanther',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top7brtivlweekly',
            name='reagenttestsloanedouttootherlabstestsavailableroche',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top7brtivlweekly',
            name='user',
            field=models.TextField(default='root', max_length=25),
        ),
        migrations.AlterField(
            model_name='top7brtiweekly',
            name='lab',
            field=models.TextField(default='brti', max_length=30),
        ),
        migrations.AlterField(
            model_name='top7brtiweekly',
            name='reagent1',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top7brtiweekly',
            name='reagent10',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top7brtiweekly',
            name='reagent11',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top7brtiweekly',
            name='reagent12',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top7brtiweekly',
            name='reagent13',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top7brtiweekly',
            name='reagent2',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top7brtiweekly',
            name='reagent3',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top7brtiweekly',
            name='reagent4',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top7brtiweekly',
            name='reagent5',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top7brtiweekly',
            name='reagent6',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top7brtiweekly',
            name='reagent7',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top7brtiweekly',
            name='reagent8',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top7brtiweekly',
            name='reagent9',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top7brtiweekly',
            name='reagenttestsloanedouttootherlabsmonthsofstockabbott',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top7brtiweekly',
            name='reagenttestsloanedouttootherlabsmonthsofstockbmx',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top7brtiweekly',
            name='reagenttestsloanedouttootherlabsmonthsofstockhologicpanther',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top7brtiweekly',
            name='reagenttestsloanedouttootherlabsmonthsofstockroche',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top7brtiweekly',
            name='reagenttestsloanedouttootherlabsreagentloanedtowhichlababbott',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top7brtiweekly',
            name='reagenttestsloanedouttootherlabsreagentloanedtowhichlabbmx',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top7brtiweekly',
            name='reagenttestsloanedouttootherlabsreagentloanedtowhichlabroche',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top7brtiweekly',
            name='reagenttestsloanedouttootherlabsstockonhandabbott',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top7brtiweekly',
            name='reagenttestsloanedouttootherlabsstockonhandbmx',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top7brtiweekly',
            name='reagenttestsloanedouttootherlabsstockonhandhologicpanther',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top7brtiweekly',
            name='reagenttestsloanedouttootherlabsstockonhandroche',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top7brtiweekly',
            name='reagenttestsloanedouttootherlabstestsavailableabbott',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top7brtiweekly',
            name='reagenttestsloanedouttootherlabstestsavailablebmx',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top7brtiweekly',
            name='reagenttestsloanedouttootherlabstestsavailablehologicpanther',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top7brtiweekly',
            name='reagenttestsloanedouttootherlabstestsavailableroche',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='top7brtiweekly',
            name='user',
            field=models.TextField(default='root', max_length=25),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedbrtivlweekly',
            name='agefemalenonpbfw15to19',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedbrtivlweekly',
            name='agefemalenonpbfw20to24',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedbrtivlweekly',
            name='agefemalenonpbfw25to49',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedbrtivlweekly',
            name='agefemalenonpbfw50plus',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedbrtivlweekly',
            name='agefemalenonpbfwlessthan15',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedbrtivlweekly',
            name='agefemalenonpbfwtotals',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedbrtivlweekly',
            name='agefemalenonpbfwunknown',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedbrtivlweekly',
            name='agefemalepbfw15to19',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedbrtivlweekly',
            name='agefemalepbfw20to24',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedbrtivlweekly',
            name='agefemalepbfw25to49',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedbrtivlweekly',
            name='agefemalepbfw50plus',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedbrtivlweekly',
            name='agefemalepbfwlessthan15',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedbrtivlweekly',
            name='agefemalepbfwtotals',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedbrtivlweekly',
            name='agefemalepbfwunknown',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedbrtivlweekly',
            name='agemale15to19',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedbrtivlweekly',
            name='agemale20to24',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedbrtivlweekly',
            name='agemale25to49',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedbrtivlweekly',
            name='agemale50plus',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedbrtivlweekly',
            name='agemalelessthan15',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedbrtivlweekly',
            name='agemaletotals',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedbrtivlweekly',
            name='agemaleunknown',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedbrtivlweekly',
            name='agetotal15to19',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedbrtivlweekly',
            name='agetotal20to24',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedbrtivlweekly',
            name='agetotal25to49',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedbrtivlweekly',
            name='agetotal50plus',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedbrtivlweekly',
            name='agetotallessthan15',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedbrtivlweekly',
            name='agetotaltotals',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedbrtivlweekly',
            name='agetotalunknown',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedbrtivlweekly',
            name='ageunknown15to19',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedbrtivlweekly',
            name='ageunknown20to24',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedbrtivlweekly',
            name='ageunknown25to49',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedbrtivlweekly',
            name='ageunknown50plus',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedbrtivlweekly',
            name='ageunknownlessthan15',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedbrtivlweekly',
            name='ageunknowntotals',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedbrtivlweekly',
            name='ageunknownunknown',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedbrtivlweekly',
            name='lab',
            field=models.TextField(default='brti', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedbrtivlweekly',
            name='user',
            field=models.TextField(default='root', max_length=25),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedbrtiweekly',
            name='agefemalenonpbfw15to19',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedbrtiweekly',
            name='agefemalenonpbfw20to24',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedbrtiweekly',
            name='agefemalenonpbfw25to49',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedbrtiweekly',
            name='agefemalenonpbfw50plus',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedbrtiweekly',
            name='agefemalenonpbfwlessthan15',
            field=models.TextField(default='.', max_length=5),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedbrtiweekly',
            name='agefemalenonpbfwtotals',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedbrtiweekly',
            name='agefemalenonpbfwunknown',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedbrtiweekly',
            name='agefemalepbfw15to19',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedbrtiweekly',
            name='agefemalepbfw20to24',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedbrtiweekly',
            name='agefemalepbfw25to49',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedbrtiweekly',
            name='agefemalepbfw50plus',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedbrtiweekly',
            name='agefemalepbfwlessthan15',
            field=models.TextField(default='.', max_length=5),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedbrtiweekly',
            name='agefemalepbfwtotals',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedbrtiweekly',
            name='agefemalepbfwunknown',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedbrtiweekly',
            name='agemale15to19',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedbrtiweekly',
            name='agemale20to24',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedbrtiweekly',
            name='agemale25to49',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedbrtiweekly',
            name='agemale50plus',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedbrtiweekly',
            name='agemalelessthan15',
            field=models.TextField(default='.', max_length=5),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedbrtiweekly',
            name='agemaletotals',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedbrtiweekly',
            name='agemaleunknown',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedbrtiweekly',
            name='agetotal15to19',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedbrtiweekly',
            name='agetotal20to24',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedbrtiweekly',
            name='agetotal25to49',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedbrtiweekly',
            name='agetotal50plus',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedbrtiweekly',
            name='agetotallessthan15',
            field=models.TextField(default='.', max_length=5),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedbrtiweekly',
            name='agetotaltotals',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedbrtiweekly',
            name='agetotalunknown',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedbrtiweekly',
            name='ageunknown15to19',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedbrtiweekly',
            name='ageunknown20to24',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedbrtiweekly',
            name='ageunknown25to49',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedbrtiweekly',
            name='ageunknown50plus',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedbrtiweekly',
            name='ageunknownlessthan15',
            field=models.TextField(default='.', max_length=5),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedbrtiweekly',
            name='ageunknowntotals',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedbrtiweekly',
            name='ageunknownunknown',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedbrtiweekly',
            name='lab',
            field=models.TextField(default='brti', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedbrtiweekly',
            name='user',
            field=models.TextField(default='root', max_length=25),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedcovid19',
            name='lab',
            field=models.TextField(default='brti', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedcovid19',
            name='machinedowntimedaysabbott',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedcovid19',
            name='machinedowntimedaysbmx',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedcovid19',
            name='machinedowntimedaysgenexpert',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedcovid19',
            name='machinedowntimedaysroche',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedcovid19',
            name='machinenumberofmachinebreakdownsabbott',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedcovid19',
            name='machinenumberofmachinebreakdownsbmx',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedcovid19',
            name='machinenumberofmachinebreakdownsgenexpert',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedcovid19',
            name='machinenumberofmachinebreakdownsroche',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedcovid19',
            name='machinereasons2abbott',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedcovid19',
            name='machinereasons2bmx',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedcovid19',
            name='machinereasons2genexpert',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedcovid19',
            name='machinereasons2roche',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedcovid19',
            name='machinereasons3abbott',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedcovid19',
            name='machinereasons3bmx',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedcovid19',
            name='machinereasons3genexpert',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedcovid19',
            name='machinereasons3roche',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedcovid19',
            name='machinereasonsabbott',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedcovid19',
            name='machinereasonsbmx',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedcovid19',
            name='machinereasonsgenexpert',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedcovid19',
            name='machinereasonsroche',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedcovid19',
            name='machinestockoutdaysabbott',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedcovid19',
            name='machinestockoutdaysbmx',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedcovid19',
            name='machinestockoutdaysgenexpert',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedcovid19',
            name='machinestockoutdaysroche',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedcovid19',
            name='user',
            field=models.TextField(default='root', max_length=25),
        ),
        migrations.AlterField(
            model_name='topbrtivlweekly',
            name='lab',
            field=models.TextField(default='brti', max_length=30),
        ),
        migrations.AlterField(
            model_name='topbrtivlweekly',
            name='laboratory',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topbrtivlweekly',
            name='month',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topbrtivlweekly',
            name='reportingweek',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topbrtivlweekly',
            name='user',
            field=models.TextField(default='root', max_length=25),
        ),
        migrations.AlterField(
            model_name='topbrtiweekly',
            name='lab',
            field=models.TextField(default='brti', max_length=30),
        ),
        migrations.AlterField(
            model_name='topbrtiweekly',
            name='laboratory',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topbrtiweekly',
            name='month',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topbrtiweekly',
            name='reportingweek',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='topbrtiweekly',
            name='user',
            field=models.TextField(default='root', max_length=25),
        ),
    ]
