# Generated by Django 3.1.7 on 2021-08-31 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20210831_0656'),
    ]

    operations = [
        migrations.CreateModel(
            name='Electricoutagebrtivleid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dayofweek', models.TextField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Monday', max_length=30)),
                ('reportingweek', models.TextField(default='.', max_length=30)),
                ('numberofhourswithnoelectricityperday', models.IntegerField(default=0)),
                ('numberofhoursgeneratorwasonperday', models.IntegerField(default=0)),
                ('litresoffueladdedtogeneratorperday', models.IntegerField(default=0)),
                ('numberofhoursmachineswasnotbeingusedduetopowercutperday', models.IntegerField(default=0)),
                ('totaltestsdoneperdayusinggenerator', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='electricoutagebrtivlweekly',
            name='lab',
        ),
        migrations.RemoveField(
            model_name='electricoutagebrtivlweekly',
            name='user',
        ),
        migrations.RemoveField(
            model_name='electricoutagebrtiweekly',
            name='lab',
        ),
        migrations.RemoveField(
            model_name='electricoutagebrtiweekly',
            name='user',
        ),
        migrations.RemoveField(
            model_name='generalbrticovid19',
            name='lab',
        ),
        migrations.RemoveField(
            model_name='generalbrticovid19',
            name='user',
        ),
        migrations.RemoveField(
            model_name='generalcovid19',
            name='lab',
        ),
        migrations.RemoveField(
            model_name='generalcovid19',
            name='user',
        ),
        migrations.RemoveField(
            model_name='machinedowntimereagentstockouttoolbrticovid19',
            name='lab',
        ),
        migrations.RemoveField(
            model_name='machinedowntimereagentstockouttoolbrticovid19',
            name='user',
        ),
        migrations.RemoveField(
            model_name='machinedowntimereagentstockouttoolcovid19',
            name='lab',
        ),
        migrations.RemoveField(
            model_name='machinedowntimereagentstockouttoolcovid19',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reasonsforfailurebrtivlweekly',
            name='lab',
        ),
        migrations.RemoveField(
            model_name='reasonsforfailurebrtivlweekly',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reasonsforfailurebrtiweekly',
            name='lab',
        ),
        migrations.RemoveField(
            model_name='reasonsforfailurebrtiweekly',
            name='user',
        ),
        migrations.RemoveField(
            model_name='specimensreceivedbrticovid19',
            name='lab',
        ),
        migrations.RemoveField(
            model_name='specimensreceivedbrticovid19',
            name='user',
        ),
        migrations.RemoveField(
            model_name='specimensreceivedbrtivleid',
            name='lab',
        ),
        migrations.RemoveField(
            model_name='specimensreceivedbrtivleid',
            name='user',
        ),
        migrations.RemoveField(
            model_name='specimensreceivedbrtiweekly',
            name='lab',
        ),
        migrations.RemoveField(
            model_name='specimensreceivedbrtiweekly',
            name='user',
        ),
        migrations.RemoveField(
            model_name='specimensrecievedbrtivlweekly',
            name='lab',
        ),
        migrations.RemoveField(
            model_name='specimensrecievedbrtivlweekly',
            name='user',
        ),
        migrations.RemoveField(
            model_name='specimensrunbrticovid19',
            name='lab',
        ),
        migrations.RemoveField(
            model_name='specimensrunbrticovid19',
            name='user',
        ),
        migrations.RemoveField(
            model_name='specimensrunbrtivleid',
            name='lab',
        ),
        migrations.RemoveField(
            model_name='specimensrunbrtivleid',
            name='user',
        ),
        migrations.RemoveField(
            model_name='specimensrunbrtivlweekly',
            name='lab',
        ),
        migrations.RemoveField(
            model_name='specimensrunbrtivlweekly',
            name='user',
        ),
        migrations.RemoveField(
            model_name='specimensrunbrtiweekly',
            name='lab',
        ),
        migrations.RemoveField(
            model_name='specimensrunbrtiweekly',
            name='user',
        ),
        migrations.RemoveField(
            model_name='top3brtivlweekly',
            name='lab',
        ),
        migrations.RemoveField(
            model_name='top3brtivlweekly',
            name='user',
        ),
        migrations.RemoveField(
            model_name='top3brtiweekly',
            name='lab',
        ),
        migrations.RemoveField(
            model_name='top3brtiweekly',
            name='user',
        ),
        migrations.RemoveField(
            model_name='top3covid19',
            name='lab',
        ),
        migrations.RemoveField(
            model_name='top3covid19',
            name='user',
        ),
        migrations.RemoveField(
            model_name='top4brtivlweekly',
            name='lab',
        ),
        migrations.RemoveField(
            model_name='top4brtivlweekly',
            name='user',
        ),
        migrations.RemoveField(
            model_name='top4brtiweekly',
            name='lab',
        ),
        migrations.RemoveField(
            model_name='top4brtiweekly',
            name='user',
        ),
        migrations.RemoveField(
            model_name='top5brtivlweekly',
            name='lab',
        ),
        migrations.RemoveField(
            model_name='top5brtivlweekly',
            name='user',
        ),
        migrations.RemoveField(
            model_name='top5brtiweekly',
            name='lab',
        ),
        migrations.RemoveField(
            model_name='top5brtiweekly',
            name='user',
        ),
        migrations.RemoveField(
            model_name='top61brtiweekly',
            name='lab',
        ),
        migrations.RemoveField(
            model_name='top61brtiweekly',
            name='user',
        ),
        migrations.RemoveField(
            model_name='top6brtivlweekly',
            name='lab',
        ),
        migrations.RemoveField(
            model_name='top6brtivlweekly',
            name='user',
        ),
        migrations.RemoveField(
            model_name='top6brtiweekly',
            name='lab',
        ),
        migrations.RemoveField(
            model_name='top6brtiweekly',
            name='user',
        ),
        migrations.RemoveField(
            model_name='top7brtivlweekly',
            name='lab',
        ),
        migrations.RemoveField(
            model_name='top7brtivlweekly',
            name='user',
        ),
        migrations.RemoveField(
            model_name='top7brtiweekly',
            name='lab',
        ),
        migrations.RemoveField(
            model_name='top7brtiweekly',
            name='user',
        ),
        migrations.RemoveField(
            model_name='topagesexdissagregationofallspecimensreceivedbrtivlweekly',
            name='lab',
        ),
        migrations.RemoveField(
            model_name='topagesexdissagregationofallspecimensreceivedbrtivlweekly',
            name='user',
        ),
        migrations.RemoveField(
            model_name='topagesexdissagregationofallspecimensreceivedbrtiweekly',
            name='lab',
        ),
        migrations.RemoveField(
            model_name='topagesexdissagregationofallspecimensreceivedbrtiweekly',
            name='user',
        ),
        migrations.RemoveField(
            model_name='topagesexdissagregationofallspecimensreceivedcovid19',
            name='lab',
        ),
        migrations.RemoveField(
            model_name='topagesexdissagregationofallspecimensreceivedcovid19',
            name='user',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='electricoutagebrtivlweekly',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='electricoutagebrtiweekly',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='generalbrticovid19',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='generalcovid19',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='machinedowntimereagentstockouttoolbrticovid19',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='machinedowntimereagentstockouttoolcovid19',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reasonsforfailurebrtivleid',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reasonsforfailurebrtivlweekly',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reasonsforfailurebrtiweekly',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='specimensreceivedbrticovid19',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='specimensreceivedbrtivleid',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='specimensreceivedbrtiweekly',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='specimensreceivedcovid19',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='specimensrecievedbrtivlweekly',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='specimensrunbrticovid19',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='specimensrunbrtivleid',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='specimensrunbrtivlweekly',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='specimensrunbrtiweekly',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='specimensruncovid19',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='top3brtivlweekly',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='top3brtiweekly',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='top3covid19',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='top4brtivlweekly',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='top4brtiweekly',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='top5brtivlweekly',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='top5brtiweekly',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='top61brtiweekly',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='top6brtivlweekly',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='top6brtiweekly',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='top7brtivlweekly',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='top7brtiweekly',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedbrtivlweekly',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedbrtiweekly',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedcovid19',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
