# Generated by Django 3.1.7 on 2021-08-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20210820_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electric_outage_brti_vl_weekly',
            name='day_of_week',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Monday', 'Tuesday'), ('Monday', 'Wednesday'), ('Monday', 'Thursday'), ('Monday', 'Friday'), ('Monday', 'Saturday'), ('Monday', 'Sunday')], default='mon', max_length=200),
        ),
    ]
