# Generated by Django 3.1.7 on 2021-08-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20210826_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specimensreceivedbrticovid19',
            name='rejectionratecurrentweek',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='specimensreceivedbrtivleid',
            name='percentagerejectionratedbs',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='specimensreceivedbrtivleid',
            name='percentagerejectionrateplasma',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='specimensreceivedbrtiweekly',
            name='percentagerejectionratedbs',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='specimensreceivedbrtiweekly',
            name='percentagerejectionrateplasma',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='specimensreceivedcovid19',
            name='rejectionratecurrentweek',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='specimensrecievedbrtivlweekly',
            name='percentagerejectionratedbs',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='specimensrecievedbrtivlweekly',
            name='percentagerejectionrateplasma',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='specimensrunbrtivleid',
            name='percentageerrorrateabbottdbs',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='specimensrunbrtivleid',
            name='percentageerrorrateabbottplasma',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='specimensrunbrtivleid',
            name='percentageerrorratebmxdbs',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='specimensrunbrtivleid',
            name='percentageerrorratebmxplasma',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='specimensrunbrtivleid',
            name='percentageerrorratehologicpantherdbs',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='specimensrunbrtivleid',
            name='percentageerrorratehologicpantherplasma',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='specimensrunbrtivleid',
            name='percentageerrorraterochedbs',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='specimensrunbrtivleid',
            name='percentageerrorraterocheplasma',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='specimensrunbrtivleid',
            name='percentagetargetsachievements',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='specimensrunbrtivlweekly',
            name='percentageerrorrateabbottdbs',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='specimensrunbrtivlweekly',
            name='percentageerrorrateabbottplasma',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='specimensrunbrtivlweekly',
            name='percentageerrorratebmxdbs',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='specimensrunbrtivlweekly',
            name='percentageerrorratebmxplasma',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='specimensrunbrtivlweekly',
            name='percentageerrorratehologicpantherdbs',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='specimensrunbrtivlweekly',
            name='percentageerrorratehologicpantherplasma',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='specimensrunbrtivlweekly',
            name='percentageerrorraterochedbs',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='specimensrunbrtivlweekly',
            name='percentageerrorraterocheplasma',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='specimensrunbrtivlweekly',
            name='percentagetargetsachievements',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='specimensrunbrtiweekly',
            name='percentageerrorrateabbottdbs',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='specimensrunbrtiweekly',
            name='percentageerrorrateabbottplasma',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='specimensrunbrtiweekly',
            name='percentageerrorratebmxdbs',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='specimensrunbrtiweekly',
            name='percentageerrorratebmxplasma',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='specimensrunbrtiweekly',
            name='percentageerrorratehologicpantherdbs',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='specimensrunbrtiweekly',
            name='percentageerrorratehologicpantherplasma',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='specimensrunbrtiweekly',
            name='percentageerrorraterochedbs',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='specimensrunbrtiweekly',
            name='percentageerrorraterocheplasma',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='specimensrunbrtiweekly',
            name='percentagetargetsachievements',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
