# Generated by Django 3.1.7 on 2021-08-31 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20210831_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalcovid19',
            name='dateofrecord',
        ),
        migrations.RemoveField(
            model_name='generalcovid19',
            name='reportingweek',
        ),
    ]
