# Generated by Django 3.1.7 on 2021-09-01 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20210901_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specimensrunbrtivlweekly',
            name='ncsnotyetclosed',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='specimensrunbrtivlweekly',
            name='totalncsfromaudit',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
