# Generated by Django 2.2.7 on 2021-08-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20210826_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalbrticovid19',
            name='generalcommentsregardingtestingandchallengesfacedbythelaboratory',
        ),
        migrations.RemoveField(
            model_name='generalcovid19',
            name='generalcommentsregardingtestingandchallengesfacedbythelaboratory',
        ),
        migrations.RemoveField(
            model_name='reasonsforfailurebrtivleid',
            name='hologicpantherplasmanumberoffailedtestsduetoreagentqualityissues',
        ),
        migrations.RemoveField(
            model_name='reasonsforfailurebrtivlweekly',
            name='hologicpantherplasmanumberoffailedtestsduetoreagentqualityissues',
        ),
        migrations.RemoveField(
            model_name='reasonsforfailurebrtiweekly',
            name='hologicpantherplasmanumberoffailedtestsduetoreagentqualityissues',
        ),
        migrations.AddField(
            model_name='generalbrticovid19',
            name='commentsregardingtestingandchallengesfacedbythelaboratory',
            field=models.TextField(default='.', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='generalcovid19',
            name='commentsregardingtestingandchallengesfacedbythelaboratory',
            field=models.TextField(default='.', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='reasonsforfailurebrtivleid',
            name='hpantherplasmanumberoffailedtestsduetoreagentqualityissues',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reasonsforfailurebrtivlweekly',
            name='hpantherplasmanumberoffailedtestsduetoreagentqualityissues',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reasonsforfailurebrtiweekly',
            name='hpantherplasmanumberoffailedtestsduetoreagentqualityissues',
            field=models.IntegerField(default=0),
        ),
    ]
