# Generated by Django 3.1.7 on 2021-09-01 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20210901_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specimensreceivedbrtivleid',
            name='samplescarriedoverpreviousweeknevertestedplasma',
        ),
        migrations.RemoveField(
            model_name='specimensrecievedbrtivlweekly',
            name='samplescarriedoverpreviousweeknevertestedplasma',
        ),
        migrations.AddField(
            model_name='specimensreceivedbrtivleid',
            name='samplescarriedoverpreviousweeksnevertestedplasma',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='specimensrecievedbrtivlweekly',
            name='samplescarriedoverpreviousweeksnevertestedplasma',
            field=models.IntegerField(default=0),
        ),
    ]
