# Generated by Django 3.1.7 on 2021-08-31 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20210831_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalbrticovid19',
            name='numberOfStaffwhotestedpositivetocovid19athubs',
            field=models.IntegerField(default=0),
        ),
    ]
