# Generated by Django 3.1.7 on 2021-08-28 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20210826_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specimensreceivedcovid19',
            name='dayofweek',
            field=models.TextField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday'), ('Total', 'Total')], default='Monday', max_length=30),
        ),
        migrations.AlterField(
            model_name='specimensruncovid19',
            name='dayofweek',
            field=models.TextField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday'), ('Total', 'Total')], default='Monday', max_length=30),
        ),
    ]
