# Generated by Django 3.1.7 on 2021-08-28 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20210828_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specimensreceivedcovid19',
            name='rejectionratecurrentweek',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
