# Generated by Django 3.2.6 on 2021-09-01 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_generalbrticovid19_numberofstaffwhotestedpositivetocovid19athubs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalbrticovid19',
            name='dateofrecord',
        ),
        migrations.RemoveField(
            model_name='machinedowntimereagentstockouttoolbrticovid19',
            name='dateofrecord',
        ),
        migrations.RemoveField(
            model_name='machinedowntimereagentstockouttoolcovid19',
            name='dateofrecord',
        ),
        migrations.RemoveField(
            model_name='reasonsforfailurebrtivleid',
            name='dateofrecord',
        ),
        migrations.RemoveField(
            model_name='specimensreceivedbrticovid19',
            name='dateofrecord',
        ),
        migrations.RemoveField(
            model_name='specimensreceivedbrtivleid',
            name='dateofrecord',
        ),
        migrations.RemoveField(
            model_name='specimensrunbrticovid19',
            name='dateofrecord',
        ),
        migrations.RemoveField(
            model_name='specimensrunbrtivleid',
            name='dateofrecord',
        ),
        migrations.AddField(
            model_name='electricoutagebrtivleid',
            name='key',
            field=models.TextField(default='vl', max_length=5),
        ),
        migrations.AddField(
            model_name='electricoutagebrtivlweekly',
            name='key',
            field=models.TextField(default='vl', max_length=30),
        ),
        migrations.AddField(
            model_name='electricoutagebrtivlweekly',
            name='user',
            field=models.TextField(default='root', max_length=25),
        ),
        migrations.AddField(
            model_name='electricoutagebrtiweekly',
            name='key',
            field=models.TextField(default='vl', max_length=30),
        ),
        migrations.AddField(
            model_name='electricoutagebrtiweekly',
            name='user',
            field=models.TextField(default='root', max_length=25),
        ),
        migrations.AddField(
            model_name='machinedowntimereagentstockouttoolcovid19',
            name='user',
            field=models.TextField(default='root', max_length=25),
        ),
        migrations.AddField(
            model_name='reasonsforfailurebrtivleid',
            name='key',
            field=models.TextField(default='vl', max_length=5),
        ),
        migrations.AddField(
            model_name='reasonsforfailurebrtivleid',
            name='lab',
            field=models.TextField(default='brti', max_length=30),
        ),
        migrations.AddField(
            model_name='reasonsforfailurebrtivlweekly',
            name='key',
            field=models.TextField(default='vl', max_length=30),
        ),
        migrations.AddField(
            model_name='reasonsforfailurebrtivlweekly',
            name='user',
            field=models.TextField(default='root', max_length=25),
        ),
        migrations.AddField(
            model_name='reasonsforfailurebrtiweekly',
            name='key',
            field=models.TextField(default='vl', max_length=30),
        ),
        migrations.AddField(
            model_name='reasonsforfailurebrtiweekly',
            name='user',
            field=models.TextField(default='root', max_length=25),
        ),
        migrations.AddField(
            model_name='specimensreceivedbrtivleid',
            name='key',
            field=models.TextField(default='vl', max_length=5),
        ),
        migrations.AddField(
            model_name='specimensreceivedbrtiweekly',
            name='key',
            field=models.TextField(default='vl', max_length=30),
        ),
        migrations.AddField(
            model_name='specimensreceivedbrtiweekly',
            name='user',
            field=models.TextField(default='root', max_length=25),
        ),
        migrations.AddField(
            model_name='specimensreceivedcovid19',
            name='lab',
            field=models.TextField(default='brti', max_length=30),
        ),
        migrations.AddField(
            model_name='specimensreceivedcovid19',
            name='user',
            field=models.TextField(default='root', max_length=25),
        ),
        migrations.AddField(
            model_name='specimensrecievedbrtivlweekly',
            name='user',
            field=models.TextField(default='root', max_length=25),
        ),
        migrations.AddField(
            model_name='specimensrunbrtivlweekly',
            name='user',
            field=models.TextField(default='root', max_length=25),
        ),
        migrations.AddField(
            model_name='specimensrunbrtiweekly',
            name='key',
            field=models.TextField(default='vl', max_length=30),
        ),
        migrations.AddField(
            model_name='specimensrunbrtiweekly',
            name='user',
            field=models.TextField(default='root', max_length=25),
        ),
        migrations.AddField(
            model_name='specimensruncovid19',
            name='dateofrecord',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='specimensruncovid19',
            name='lab',
            field=models.TextField(default='brti', max_length=30),
        ),
        migrations.AddField(
            model_name='specimensruncovid19',
            name='reportingweek',
            field=models.TextField(default='.', max_length=30),
        ),
        migrations.AddField(
            model_name='specimensruncovid19',
            name='user',
            field=models.TextField(default='root', max_length=25),
        ),
        migrations.AddField(
            model_name='top3brtivlweekly',
            name='user',
            field=models.TextField(default='root', max_length=25),
        ),
        migrations.AddField(
            model_name='top3brtiweekly',
            name='key',
            field=models.TextField(default='vl', max_length=30),
        ),
        migrations.AddField(
            model_name='top3brtiweekly',
            name='user',
            field=models.TextField(default='root', max_length=25),
        ),
        migrations.AddField(
            model_name='top3covid19',
            name='key',
            field=models.TextField(default='vl', max_length=30),
        ),
        migrations.AddField(
            model_name='top3covid19',
            name='user',
            field=models.TextField(default='root', max_length=25),
        ),
        migrations.AddField(
            model_name='top4brtivlweekly',
            name='user',
            field=models.TextField(default='root', max_length=25),
        ),
        migrations.AddField(
            model_name='top4brtiweekly',
            name='key',
            field=models.TextField(default='vl', max_length=30),
        ),
        migrations.AddField(
            model_name='top4brtiweekly',
            name='user',
            field=models.TextField(default='root', max_length=25),
        ),
        migrations.AddField(
            model_name='top5brtivlweekly',
            name='user',
            field=models.TextField(default='root', max_length=25),
        ),
        migrations.AddField(
            model_name='top5brtiweekly',
            name='key',
            field=models.TextField(default='vl', max_length=30),
        ),
        migrations.AddField(
            model_name='top5brtiweekly',
            name='user',
            field=models.TextField(default='root', max_length=25),
        ),
        migrations.AddField(
            model_name='top61brtiweekly',
            name='key',
            field=models.TextField(default='vl', max_length=30),
        ),
        migrations.AddField(
            model_name='top61brtiweekly',
            name='user',
            field=models.TextField(default='root', max_length=25),
        ),
        migrations.AddField(
            model_name='top6brtivlweekly',
            name='user',
            field=models.TextField(default='root', max_length=25),
        ),
        migrations.AddField(
            model_name='top6brtiweekly',
            name='key',
            field=models.TextField(default='vl', max_length=30),
        ),
        migrations.AddField(
            model_name='top6brtiweekly',
            name='user',
            field=models.TextField(default='root', max_length=25),
        ),
        migrations.AddField(
            model_name='top7brtivlweekly',
            name='dateofrecord',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='top7brtivlweekly',
            name='user',
            field=models.TextField(default='root', max_length=25),
        ),
        migrations.AddField(
            model_name='top7brtiweekly',
            name='key',
            field=models.TextField(default='vl', max_length=30),
        ),
        migrations.AddField(
            model_name='top7brtiweekly',
            name='user',
            field=models.TextField(default='root', max_length=25),
        ),
        migrations.AddField(
            model_name='topagesexdissagregationofallspecimensreceivedbrtivlweekly',
            name='user',
            field=models.TextField(default='root', max_length=25),
        ),
        migrations.AddField(
            model_name='topagesexdissagregationofallspecimensreceivedbrtiweekly',
            name='key',
            field=models.TextField(default='vl', max_length=30),
        ),
        migrations.AddField(
            model_name='topagesexdissagregationofallspecimensreceivedbrtiweekly',
            name='user',
            field=models.TextField(default='root', max_length=25),
        ),
        migrations.AddField(
            model_name='topagesexdissagregationofallspecimensreceivedcovid19',
            name='key',
            field=models.TextField(default='vl', max_length=30),
        ),
        migrations.AddField(
            model_name='topagesexdissagregationofallspecimensreceivedcovid19',
            name='user',
            field=models.TextField(default='root', max_length=25),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='electricoutagebrtivleid',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='electricoutagebrtivlweekly',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='electricoutagebrtiweekly',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='generalbrticovid19',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='generalcovid19',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='machinedowntimereagentstockouttoolbrticovid19',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='machinedowntimereagentstockouttoolcovid19',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reasonsforfailurebrtivleid',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reasonsforfailurebrtivlweekly',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reasonsforfailurebrtiweekly',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='specimensreceivedbrticovid19',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='specimensreceivedbrtivleid',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='specimensreceivedbrtiweekly',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='specimensreceivedcovid19',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='specimensrecievedbrtivlweekly',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='specimensrunbrticovid19',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='specimensrunbrtivleid',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='specimensrunbrtivlweekly',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='specimensrunbrtiweekly',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='specimensruncovid19',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='top3brtivlweekly',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='top3brtiweekly',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='top3covid19',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='top4brtivlweekly',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='top4brtiweekly',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='top5brtivlweekly',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='top5brtiweekly',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='top61brtiweekly',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='top6brtivlweekly',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='top6brtiweekly',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='top7brtivlweekly',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='top7brtiweekly',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedbrtivlweekly',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedbrtiweekly',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='topagesexdissagregationofallspecimensreceivedcovid19',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
