# Generated by Django 3.1.7 on 2021-09-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20210901_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='specimensrunbrtivleid',
            name='hpantherplasmanumberoffailedtestsduetoreagentqualityissues',
            field=models.IntegerField(default=0),
        ),
    ]
