# Generated by Django 3.1.7 on 2021-09-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_specimensrunbrtivleid_hpantherplasmanumberoffailedtestsduetoreagentqualityissues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricoutagebrtivleid',
            name='dayofweek',
            field=models.TextField(choices=[('NMRL', 'NMRL'), ('Mpilo', 'Mpilo'), ('BRIDH', 'BRIDH'), ('NTBRL', 'NTBRL'), ('Gweru', 'Gweru'), ('Chinhoyi', 'Chinhoyi'), ('Masvingo', 'Masvingo'), ('eid', 'eid'), ('Victoria Falls', 'Victoria Falls'), ('Bindura', 'Bindura'), ('Kadoma', 'Kadoma'), ('Marondera', 'Marondera'), ('St Lukes', 'St Lukes'), ('Gwanda', 'Gwanda'), ('Total', 'Total')], default='Monday', max_length=30),
        ),
    ]
