# Generated by Django 3.1.7 on 2021-09-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20210901_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalbrticovid19',
            name='commentsoninteruptions',
            field=models.TextField(default='.', max_length=3000),
        ),
        migrations.AddField(
            model_name='generalcovid19',
            name='commentsoninteruptions',
            field=models.TextField(default='.', max_length=3000),
        ),
        migrations.AlterField(
            model_name='generalbrticovid19',
            name='Comments',
            field=models.TextField(default='null', max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='generalbrticovid19',
            name='Requesttobrtifromthelaboratory',
            field=models.TextField(default='.', max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='generalbrticovid19',
            name='commentsregardingtestingandchallengesfacedbythelaboratory',
            field=models.TextField(default='.', max_length=3000, null=True),
        ),
    ]
